name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama donde tengas tu web

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Si quisieras hacer build (ej. React, Vite, etc.), acá va el build
      # Para tu caso (HTML + JS + Firebase), no hace falta compilar

      - name: Subir artefactos
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Publicar todo el repo (HTML, CSS, JS)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
